### ISSUE TITLE
[Testing] DocumentPredicateTest periodically fails

### ISSUE THREAD

**Issue by dsukhoroslov** [dsukhoroslov/bagri#139]
looks like race conditions:
```
Tests run: 4, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 13.285 sec <<< FAILURE! - in com.bagri.server.hazelcast.predicate.DocumentPredicateTest
testLimitPredicate(com.bagri.server.hazelcast.predicate.DocumentPredicateTest)  Time elapsed: 0.09 sec  <<< FAILURE!
java.lang.AssertionError: expected:<15> but was:<5>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.bagri.server.hazelcast.predicate.DocumentPredicateTest.testLimitPredicate(DocumentPredicateTest.java:113)

testCollectionPredicate(com.bagri.server.hazelcast.predicate.DocumentPredicateTest)  Time elapsed: 0.07 sec  <<< FAILURE!
java.lang.AssertionError: expected:<100> but was:<44>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.bagri.server.hazelcast.predicate.DocumentPredicateTest.testCollectionPredicate(DocumentPredicateTest.java:104)

testAttributePredicate(com.bagri.server.hazelcast.predicate.DocumentPredicateTest)  Time elapsed: 0.068 sec  <<< FAILURE!
java.lang.AssertionError: expected:<23> but was:<9>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.bagri.server.hazelcast.predicate.DocumentPredicateTest.testAttributePredicate(DocumentPredicateTest.java:95)
```
from IDE the same test usualy pass

**Comment by dsukhoroslov** [comment]
fixed
