### ISSUE TITLE
Test error causes subsequent tests failure

### ISSUE THREAD

**Issue by dsukhoroslov** [dsukhoroslov/bagri#14]
After first error in junit test all other tests are failed with `nested transactions are not supported` error: 

```
Tests run: 9, Failures: 0, Errors: 8, Skipped: 0, Time elapsed: 4.372 sec <<< FAILURE! - in com.bagri.xdm.cache.hazelcast.impl.UniqueIndexManagementTest
uniqueDocumentUpdateTest(com.bagri.xdm.cache.hazelcast.impl.UniqueIndexManagementTest)  Time elapsed: 0.015 sec  <<< ERROR!
com.bagri.xdm.api.XDMException: unique index 'IDX_Security_Symbol' violated for docId: -7949185888741752831, pathId: 1, value: VFINX
	at com.bagri.xdm.cache.hazelcast.impl.IndexManagementImpl.indexPath(IndexManagementImpl.java:298)
	at com.bagri.xdm.cache.hazelcast.impl.IndexManagementImpl.addIndex(IndexManagementImpl.java:257)
	at com.bagri.xdm.cache.hazelcast.impl.DocumentManagementImpl.loadElements(DocumentManagementImpl.java:626)
	at com.bagri.xdm.cache.hazelcast.impl.DocumentManagementImpl.createDocument(DocumentManagementImpl.java:512)
	at com.bagri.xdm.cache.hazelcast.impl.DocumentManagementImpl.storeDocumentFromString(DocumentManagementImpl.java:794)
	at com.bagri.xdm.api.test.XDMManagementTest.updateDocumentTest(XDMManagementTest.java:94)
	at com.bagri.xdm.cache.hazelcast.impl.UniqueIndexManagementTest.uniqueDocumentUpdateTest(UniqueIndexManagementTest.java:148)

uniqueDocumentUpdateTest(com.bagri.xdm.cache.hazelcast.impl.UniqueIndexManagementTest)  Time elapsed: 0.015 sec  <<< ERROR!
com.bagri.xdm.api.XDMException: nested transactions are not supported; current txId: 5
	at com.bagri.xdm.cache.hazelcast.impl.TransactionManagementImpl.beginTransaction(TransactionManagementImpl.java:120)
	at com.bagri.xdm.cache.hazelcast.impl.TransactionManagementImpl.beginTransaction(TransactionManagementImpl.java:112)
	at com.bagri.xdm.api.test.XDMManagementTest.removeDocumentsTest(XDMManagementTest.java:73)
	at com.bagri.xdm.cache.hazelcast.impl.UniqueIndexManagementTest.tearDown(UniqueIndexManagementTest.java:88)
```

**Comment by dsukhoroslov** [comment]
fixed. XDMTransactionManagement API extended to handle such case
