### ISSUE TITLE
[Testing] error when getting documents

### ISSUE THREAD

**Issue by dsukhoroslov** [dsukhoroslov/bagri#146]
add documents to DB via insTpox, then get docs via getTpox scripts. on the second phase there are a lot of exceptions:
```
2018-01-17 17:33:46.813 [Thread-4] ERROR com.bagri.test.tpox.workload.BagriXQJPlugin - execute.error
javax.xml.xquery.XQException: java.util.concurrent.ExecutionException: com.hazelcast.core.HazelcastException: com.bagri.core.api.BagriException: Problem while reading DataSerializable, namespace: 2000, id: 110, class: 'null', exception: null;
        at com.bagri.support.util.XQUtils.getXQException(XQUtils.java:649) ~[bagri-core-1.2.0-RC1.jar:na]
        at com.bagri.xquery.saxon.XQProcessorClient.executeXQuery(XQProcessorClient.java:98) ~[bagri-xquery-saxon-1.2.0-RC1.jar:na]
        at com.bagri.xqj.BagriXQConnection.executeQuery(BagriXQConnection.java:371) ~[bagri-xqj-1.2.0-RC1.jar:na]
        at com.bagri.xqj.BagriXQPreparedExpression.executeQuery(BagriXQPreparedExpression.java:83) ~[bagri-xqj-1.2.0-RC1.jar:na]
        at com.bagri.test.tpox.workload.BagriXQJPlugin.execQuery(BagriXQJPlugin.java:133) ~[bagri-test-tpox-1.2.0-RC1.jar:na]
        at com.bagri.test.tpox.workload.BagriTPoXPlugin.execute(BagriTPoXPlugin.java:135) ~[bagri-test-tpox-1.2.0-RC1.jar:na]
        at net.sf.tpox.workload.core.ConcurrentUser.processTransaction(Unknown Source) [tpox-workload-2.1.jar:na]
        at net.sf.tpox.workload.core.ConcurrentUser.executeWorkload(Unknown Source) [tpox-workload-2.1.jar:na]
        at net.sf.tpox.workload.core.ConcurrentUser.run(Unknown Source) [tpox-workload-2.1.jar:na]
Caused by: com.bagri.core.api.BagriException: java.util.concurrent.ExecutionException: com.hazelcast.core.HazelcastException: com.bagri.core.api.BagriException: Problem while reading DataSerializable, namespace: 2000, id: 110, class: 'null', exception: null
        at com.bagri.client.hazelcast.impl.QueryManagementImpl.getResults(QueryManagementImpl.java:228) ~[bagri-client-hazelcast-1.2.0-RC1.jar:na]
        at com.bagri.client.hazelcast.impl.QueryManagementImpl.executeQuery(QueryManagementImpl.java:185) ~[bagri-client-hazelcast-1.2.0-RC1.jar:na]
        at com.bagri.xquery.saxon.XQProcessorClient.executeXQuery(XQProcessorClient.java:96) ~[bagri-xquery-saxon-1.2.0-RC1.jar:na]
        ... 7 common frames omitted
Caused by: java.util.concurrent.ExecutionException: com.hazelcast.core.HazelcastException: com.bagri.core.api.BagriException: Problem while reading DataSerializable, namespace: 2000, id: 110, class: 'null', exception: null
        at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:108) ~[hazelcast-all-3.8.7.jar:3.8.7]
        at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:32) ~[hazelcast-all-3.8.7.jar:3.8.7]
        at com.hazelcast.spi.impl.AbstractInvocationFuture.get(AbstractInvocationFuture.java:183) ~[hazelcast-all-3.8.7.jar:3.8.7]
        at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:127) ~[hazelcast-all-3.8.7.jar:3.8.7]
        at com.hazelcast.client.util.ClientDelegatingFuture.get(ClientDelegatingFuture.java:118) ~[hazelcast-all-3.8.7.jar:3.8.7]
        at com.bagri.client.hazelcast.impl.QueryManagementImpl.getResults(QueryManagementImpl.java:201) ~[bagri-client-hazelcast-1.2.0-RC1.jar:na]
        ... 9 common frames omitted
Caused by: com.hazelcast.core.HazelcastException: com.bagri.core.api.BagriException: Problem while reading DataSerializable, namespace: 2000, id: 110, class: 'null', exception: null
        at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:94) ~[hazelcast-all-3.8.7.jar:3.8.7]
        at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:56) ~[hazelcast-all-3.8.7.jar:3.8.7]
        at com.hazelcast.util.ExceptionUtil.peel(ExceptionUtil.java:52) ~[hazelcast-all-3.8.7.jar:3.8.7]
        at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.sendClientMessage(AbstractMessageTask.java:218) ~[hazelcast-all-3.8.7.jar:3.8.7]
        at com.hazelcast.client.impl.protocol.task.AbstractMessageTask.handleProcessingFailure(AbstractMessageTask.java:162) ~[hazelcast-all-3.8.7.jar:3.8.7]
        at com.hazelcast.client.impl.protocol.task.AbstractInvocationMessageTask.onFailure(AbstractInvocationMessageTask.java:56) ~[hazelcast-all-3.8.7.jar:3.8.7]
        at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:246) ~[hazelcast-all-3.8.7.jar:3.8.7]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_74]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_74]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_74]
        at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64) ~[hazelcast-all-3.8.7.jar:3.8.7]
        at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80) ~[hazelcast-all-3.8.7.jar:3.8.7]
        at ------ submitted from ------.(Unknown Source) ~[na:na]
        at com.hazelcast.client.spi.impl.ClientInvocationFuture.resolveAndThrowIfException(ClientInvocationFuture.java:95) ~[hazelcast-all-3.8.7.jar:3.8.7]
        ... 14 common frames omitted
Caused by: com.hazelcast.client.UndefinedErrorCodeException: Class name : com.bagri.core.api.BagriException , Message :Problem while reading DataSerializable, namespace: 2000, id: 110, class: 'null', exception: null
        at com.bagri.server.hazelcast.impl.QueryManagementImpl.executeQuery(QueryManagementImpl.java:702) ~[na:na]
        at com.bagri.server.hazelcast.task.query.QueryExecutor.call(QueryExecutor.java:50) ~[na:na]
        at com.bagri.server.hazelcast.task.query.QueryExecutor.call(QueryExecutor.java:21) ~[na:na]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_74]
        at com.hazelcast.executor.impl.DistributedExecutorService$CallableProcessor.run(DistributedExecutorService.java:241) ~[hazelcast-all-3.8.7.jar:3.8.7]
        at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:227) ~[hazelcast-all-3.8.7.jar:3.8.7]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_74]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_74]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_74]
        at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64) ~[hazelcast-all-3.8.7.jar:3.8.7]
        at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80) ~[hazelcast-all-3.8.7.jar:3.8.7]
        at ------ submitted from ------.(Unknown Source) ~[na:na]
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolve(InvocationFuture.java:114) ~[hazelcast-all-3.8.7.jar:3.8.7]
        at com.hazelcast.spi.impl.AbstractInvocationFuture$1.run(AbstractInvocationFuture.java:243) ~[hazelcast-all-3.8.7.jar:3.8.7]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_74]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_74]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_74]
        at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:64) ~[hazelcast-all-3.8.7.jar:3.8.7]
        at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:80) ~[hazelcast-all-3.8.7.jar:3.8.7]
```

**Comment by dsukhoroslov** [comment]
it happens in cluster only, no issues on one node at all

**Comment by dsukhoroslov** [comment]
fixed
