### ISSUE TITLE
can not run XQuery on XMark schema with 2 (or more?)  nodes

### ISSUE THREAD

**Issue by dsukhoroslov** [dsukhoroslov/bagri#16]
```
     [java] 2016-06-06 13:09:41.292 [cached11] INFO  com.bagri.xdm.cache.hazelcast.impl.DocumentManagementImpl - getDocumentAsString; can not find active document for uri: auction.xml
     [java] Error on line 1 column 24 of file:/C:/Work/Bagri/git/bagri/etc/samples/xmark/:
     [java]   FODC0002: cannot resolve document for URI:
     [java]   file:/C:/Work/Bagri/git/bagri/etc/samples/xmark/auction.xml
     [java] 2016-06-06 13:09:41.300 [cached11] ERROR com.bagri.xquery.saxon.XQProcessorServer - execQuery.error:
     [java] net.sf.saxon.trans.XPathException: cannot resolve document for URI: file:/C:/Work/Bagri/git/bagri/etc/sample
s/xmark/auction.xml
     [java]     at com.bagri.xquery.saxon.SourceResolverImpl.resolveSource(SourceResolverImpl.java:91) ~[bagri-xquery-saxon-0.8.1-SNAPSHOT.jar:na]
     [java]     at net.sf.saxon.functions.DocumentFn.makeDoc(DocumentFn.java:324) ~[Saxon-HE-9.7.0-4.jar:na]
     [java]     at net.sf.saxon.functions.Doc.call(Doc.java:94) ~[Saxon-HE-9.7.0-4.jar:na]
     [java]     at net.sf.saxon.functions.Doc.call(Doc.java:26) ~[Saxon-HE-9.7.0-4.jar:na]
     [java]     at net.sf.saxon.expr.FunctionCall.iterate(FunctionCall.java:546) ~[Saxon-HE-9.7.0-4.jar:na]
     [java]     at net.sf.saxon.expr.Expression.evaluateItem(Expression.java:754) ~[Saxon-HE-9.7.0-4.jar:na]
     [java]     at net.sf.saxon.expr.SimpleStepExpression.iterate(SimpleStepExpression.java:106) ~[Saxon-HE-9.7.0-4.jar:na]
     [java]     at net.sf.saxon.expr.SlashExpression.iterate(SlashExpression.java:869) ~[Saxon-HE-9.7.0-4.jar:na]
     [java]     at net.sf.saxon.expr.SlashExpression.iterate(SlashExpression.java:869) ~[Saxon-HE-9.7.0-4.jar:na]
     [java]     at net.sf.saxon.expr.FilterExpression.iterate(FilterExpression.java:1172) ~[Saxon-HE-9.7.0-4.jar:na]
     [java]     at net.sf.saxon.expr.ForExpression.iterate(ForExpression.java:443) ~[Saxon-HE-9.7.0-4.jar:na]
     [java]     at net.sf.saxon.query.XQueryExpression.iterator(XQueryExpression.java:317) ~[Saxon-HE-9.7.0-4.jar:na]
     [java]     at com.bagri.xquery.saxon.XQProcessorServer.execQuery(XQProcessorServer.java:164) [bagri-xquery-saxon-0.8.1-SNAPSHOT.jar:na]
     [java]     at com.bagri.xquery.saxon.XQProcessorServer.executeXQuery(XQProcessorServer.java:210) [bagri-xquery-saxon-0.8.1-SNAPSHOT.jar:na]
     [java]     at com.bagri.xdm.cache.hazelcast.impl.QueryManagementImpl.runQuery(QueryManagementImpl.java:649) [classes/:na]
     [java]     at com.bagri.xdm.cache.hazelcast.impl.QueryManagementImpl.executeQuery(QueryManagementImpl.java:597) [classes/:na]
     [java]     at com.bagri.xdm.cache.hazelcast.task.query.QueryExecutor$1.call(QueryExecutor.java:54) [classes/:na]
     [java]     at com.bagri.xdm.cache.hazelcast.task.query.QueryExecutor$1.call(QueryExecutor.java:51) [classes/:na]
     [java]     at com.bagri.xdm.cache.hazelcast.impl.TransactionManagementImpl.callInTransaction(TransactionManagementImpl.java:305) [classes/:na]
     [java]     at com.bagri.xdm.cache.hazelcast.task.query.QueryExecutor.call(QueryExecutor.java:51) [classes/:na]
     [java]     at com.bagri.xdm.cache.hazelcast.task.query.QueryExecutor.call(QueryExecutor.java:17) [classes/:na]
     [java]     at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_74]
     [java]     at com.hazelcast.executor.impl.DistributedExecutorService$CallableProcessor.run(DistributedExecutorService.java:203) [hazelcast-all-3.6.3.jar:3.6.3]
     [java]     at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:212) [hazelcast-all-3.6.3.jar:3.6.3]
     [java]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_74]
     [java]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_74]
     [java]     at java.lang.Thread.run(Thread.java:745) [na:1.8.0_74]
     [java]     at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) [hazelcast-all-3.6.3.jar:3.6.3]
     [java]     at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92) [hazelcast-all-3.6.3.jar:3.6.3]
     [java] 2016-06-06 13:09:41.302 [cached11] ERROR com.bagri.xdm.cache.hazelcast.impl.TransactionManagementImpl - call
InTransaction.error; in transaction: 1
     [java] com.bagri.xdm.api.XDMException: javax.xml.xquery.XQException: cannot resolve document for URI: file:/C:/Work
/Bagri/git/bagri/etc/samples/xmark/auction.xml
     [java]     at com.bagri.xdm.cache.hazelcast.impl.QueryManagementImpl.executeQuery(QueryManagementImpl.java:601) ~[classes/:na]
     [java]     at com.bagri.xdm.cache.hazelcast.task.query.QueryExecutor$1.call(QueryExecutor.java:54) ~[classes/:na]
     [java]     at com.bagri.xdm.cache.hazelcast.task.query.QueryExecutor$1.call(QueryExecutor.java:51) ~[classes/:na]
     [java]     at com.bagri.xdm.cache.hazelcast.impl.TransactionManagementImpl.callInTransaction(TransactionManagementImpl.java:305) ~[classes/:na]
     [java]     at com.bagri.xdm.cache.hazelcast.task.query.QueryExecutor.call(QueryExecutor.java:51) [classes/:na]
     [java]     at com.bagri.xdm.cache.hazelcast.task.query.QueryExecutor.call(QueryExecutor.java:17) [classes/:na]
     [java]     at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_74]
     [java]     at com.hazelcast.executor.impl.DistributedExecutorService$CallableProcessor.run(DistributedExecutorService.java:203) [hazelcast-all-3.6.3.jar:3.6.3]
     [java]     at com.hazelcast.util.executor.CachedExecutorServiceDelegate$Worker.run(CachedExecutorServiceDelegate.java:212) [hazelcast-all-3.6.3.jar:3.6.3]
     [java]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_74]
     [java]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_74]
     [java]     at java.lang.Thread.run(Thread.java:745) [na:1.8.0_74]
     [java]     at com.hazelcast.util.executor.HazelcastManagedThread.executeRun(HazelcastManagedThread.java:76) [hazelcast-all-3.6.3.jar:3.6.3]
     [java]     at com.hazelcast.util.executor.HazelcastManagedThread.run(HazelcastManagedThread.java:92) [hazelcast-all-3.6.3.jar:3.6.3]
     [java] Caused by: javax.xml.xquery.XQException: cannot resolve document for URI: file:/C:/Work/Bagri/git/bagri/etc/
samples/xmark/auction.xml
     [java]     at com.bagri.xdm.cache.hazelcast.impl.QueryManagementImpl.runQuery(QueryManagementImpl.java:677) ~[classes/:na]
     [java]     at com.bagri.xdm.cache.hazelcast.impl.QueryManagementImpl.executeQuery(QueryManagementImpl.java:597) ~[classes/:na]
     [java]     ... 13 common frames omitted
```
Note: there are no issues on this schema with the same queries when # of nodes = 1

**Comment by dsukhoroslov** [comment]
fixed
