### ISSUE TITLE
[VVMP] exception at document content retrieve

### ISSUE THREAD

**Issue by dsukhoroslov** [dsukhoroslov/bagri#55]
```
com.bagri.tools.vvm.service.ServiceException: javax.management.ReflectionException: Target method not found: com.bagri.xdm.cache.hazelcast.management.DocumentManagement.getDocumentContent
	at com.bagri.tools.vvm.service.DocumentServiceProvider.getDocumentContent(DocumentServiceProvider.java:217)
	at com.bagri.tools.vvm.ui.SchemaDocumentPanel.selectDocument(SchemaDocumentPanel.java:398)

Caused by: java.lang.NoSuchMethodException: com.bagri.xdm.cache.hazelcast.management.DocumentManagement.getDocumentContent(java.lang.String)
```
looks like the plugin was not adjusted to the recent API change.

**Comment by dsukhoroslov** [comment]
fixed
