### ISSUE TITLE
[VVMP] Connection exception in baagri plugin

### ISSUE THREAD

**Issue by dsukhoroslov** [dsukhoroslov/bagri#56]
It happens rarely. The workaround is to restart VVM console, no need to restart any Bagri component. The exception is:

```
com.bagri.tools.vvm.service.ServiceException: java.rmi.ConnectException: Connection refused to host: 10.10.59.20; nested exception is: 
	java.net.ConnectException: Connection refused: connect
	at com.bagri.tools.vvm.service.ClusterServiceProvider.getNodes(ClusterServiceProvider.java:72)
	at com.bagri.tools.vvm.ui.BagriMainPanel.createTree(BagriMainPanel.java:115)
	at com.bagri.tools.vvm.ui.BagriMainPanel.<init>(BagriMainPanel.java:58)
	at com.bagri.tools.vvm.manager.BagriManagerView.createComponent(BagriManagerView.java:68)
	at com.sun.tools.visualvm.core.ui.DataSourceView.getView(DataSourceView.java:184)
	at com.sun.tools.visualvm.core.ui.DataSourceWindowTabbedPane$ViewContainer.<init>(DataSourceWindowTabbedPane.java:582)
	at com.sun.tools.visualvm.core.ui.DataSourceWindowTabbedPane.addViewTab(DataSourceWindowTabbedPane.java:117)
	at com.sun.tools.visualvm.core.ui.DataSourceWindow.addView(DataSourceWindow.java:89)
	at com.sun.tools.visualvm.core.ui.DataSourceWindowManager$7.run(DataSourceWindowManager.java:267)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.rmi.ConnectException: Connection refused to host: 10.10.59.20; nested exception is: 
	java.net.ConnectException: Connection refused: connect
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:619)
	at sun.rmi.transport.tcp.TCPChannel.createConnection(TCPChannel.java:216)
	at sun.rmi.transport.tcp.TCPChannel.newConnection(TCPChannel.java:202)
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:130)
	at com.sun.jmx.remote.internal.PRef.invoke(Unknown Source)
	at javax.management.remote.rmi.RMIConnectionImpl_Stub.queryMBeans(Unknown Source)
	at javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.queryMBeans(RMIConnector.java:827)
	at sun.reflect.GeneratedMethodAccessor96.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.tools.visualvm.jmx.impl.JmxModelImpl$CheckerInvocationHandler.invoke(JmxModelImpl.java:634)
	at com.sun.proxy.$Proxy10.queryMBeans(Unknown Source)
	at com.bagri.tools.vvm.service.ClusterServiceProvider.getNodes(ClusterServiceProvider.java:63)
	... 22 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at sun.rmi.transport.proxy.RMIDirectSocketFactory.createSocket(RMIDirectSocketFactory.java:40)
	at sun.rmi.transport.proxy.RMIMasterSocketFactory.createSocket(RMIMasterSocketFactory.java:148)
	at sun.rmi.transport.tcp.TCPEndpoint.newSocket(TCPEndpoint.java:613)
	... 34 more
```

**Comment by dsukhoroslov** [comment]
still happens time to time, looks like VVM issue
