### ISSUE TITLE
[Core] error on TransactionStore initialization

### ISSUE THREAD

**Issue by dsukhoroslov** [dsukhoroslov/bagri#60]
```
2016-08-31 17:37:52.649 [hz.Mongo.partition-operation.thread-0] ERROR com.bagri.xdm.cache.hazelcast.store.TransactionCacheStore - init.error
java.io.FileNotFoundException: ..\data\mongo\txlog0.xdb (The system cannot find the path specified)
	at java.io.RandomAccessFile.open0(Native Method) ~[na:1.8.0_74]
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316) ~[na:1.8.0_74]
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243) ~[na:1.8.0_74]
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:124) ~[na:1.8.0_74]
	at com.bagri.xdm.cache.hazelcast.store.TransactionCacheStore.init(TransactionCacheStore.java:65) ~[bagri-server-hazelcast-1.0.0-EA1.jar:1.0.0-EA1]
	at com.hazelcast.map.impl.MapStoreWrapper.init(MapStoreWrapper.java:72) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.map.impl.mapstore.BasicMapStoreContext.callLifecycleSupportInit(BasicMapStoreContext.java:174) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.map.impl.mapstore.BasicMapStoreContext.create(BasicMapStoreContext.java:139) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.map.impl.mapstore.MapStoreContextFactory.createMapStoreContext(MapStoreContextFactory.java:48) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.map.impl.MapContainer.<init>(MapContainer.java:102) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.map.impl.MapServiceContextImpl$1.createNew(MapServiceContextImpl.java:88) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.map.impl.MapServiceContextImpl$1.createNew(MapServiceContextImpl.java:83) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.util.ConcurrencyUtil.getOrPutSynchronized(ConcurrencyUtil.java:61) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.map.impl.MapServiceContextImpl.getMapContainer(MapServiceContextImpl.java:156) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.map.impl.operation.AddIndexOperation.run(AddIndexOperation.java:61) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:172) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processOperation(OperationThread.java:198) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:132) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:124) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:99) [hazelcast-all-3.6.4.jar:3.6.4]
2016-08-31 17:37:52.654 [hz.Mongo.partition-operation.thread-0] ERROR com.hazelcast.map.impl.operation.AddIndexOperation - [localhost]:10300 [Mongo] [3.6.4] Cannot initialize Transaction Store
java.lang.RuntimeException: Cannot initialize Transaction Store
	at com.bagri.xdm.cache.hazelcast.store.TransactionCacheStore.init(TransactionCacheStore.java:86) ~[bagri-server-hazelcast-1.0.0-EA1.jar:1.0.0-EA1]
	at com.hazelcast.map.impl.MapStoreWrapper.init(MapStoreWrapper.java:72) ~[hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.map.impl.mapstore.BasicMapStoreContext.callLifecycleSupportInit(BasicMapStoreContext.java:174) ~[hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.map.impl.mapstore.BasicMapStoreContext.create(BasicMapStoreContext.java:139) ~[hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.map.impl.mapstore.MapStoreContextFactory.createMapStoreContext(MapStoreContextFactory.java:48) ~[hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.map.impl.MapContainer.<init>(MapContainer.java:102) ~[hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.map.impl.MapServiceContextImpl$1.createNew(MapServiceContextImpl.java:88) ~[hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.map.impl.MapServiceContextImpl$1.createNew(MapServiceContextImpl.java:83) ~[hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.util.ConcurrencyUtil.getOrPutSynchronized(ConcurrencyUtil.java:61) ~[hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.map.impl.MapServiceContextImpl.getMapContainer(MapServiceContextImpl.java:156) ~[hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.map.impl.operation.AddIndexOperation.run(AddIndexOperation.java:61) ~[hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.spi.impl.operationservice.impl.OperationRunnerImpl.run(OperationRunnerImpl.java:172) ~[hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.processOperation(OperationThread.java:198) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.process(OperationThread.java:132) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.doRun(OperationThread.java:124) [hazelcast-all-3.6.4.jar:3.6.4]
	at com.hazelcast.spi.impl.operationexecutor.classic.OperationThread.run(OperationThread.java:99) [hazelcast-all-3.6.4.jar:3.6.4]
Caused by: java.io.FileNotFoundException: ..\data\mongo\txlog0.xdb (The system cannot find the path specified)
	at java.io.RandomAccessFile.open0(Native Method) ~[na:1.8.0_74]
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316) ~[na:1.8.0_74]
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243) ~[na:1.8.0_74]
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:124) ~[na:1.8.0_74]
	at com.bagri.xdm.cache.hazelcast.store.TransactionCacheStore.init(TransactionCacheStore.java:65) ~[bagri-server-hazelcast-1.0.0-EA1.jar:1.0.0-EA1]
	... 15 common frames omitted
```
check that folder ..\data\mongo exist!

**Comment by dsukhoroslov** [comment]
this is a correct behaviour, actually. removed extra logging.
