### ISSUE TITLE
[REST] error on building dynamic resource

### ISSUE THREAD

**Issue by dsukhoroslov** [dsukhoroslov/bagri#67]
```
2016-10-10 20:30:37.058 [hz.client_1.user-1] INFO  com.hazelcast.core.LifecycleService - hz.client_1 [TPoX] [3.7.2] HazelcastClient 3.7.2 (20161004 - 540b01c) is CLIENT_CONNECTED
2016-10-10 20:30:37.059 [qtp388444787-80] INFO  com.bagri.xdm.client.hazelcast.impl.ClientManagementImpl - connect; new HZ instance created for clientId: dce06b6a-3228-47c5-891d-8079e80c08ce
2016-10-10 20:30:37.293 [Thread-10] INFO  com.bagri.xquery.saxon.XQCompilerImpl - getModuleExpression.error; message: java.io.FileNotFoundException: /home/bagri/apps/bagri-1.1.0-SNAPSHOT/bin/rest_module (No such file or directory)
/home/bagri/apps/bagri-1.1.0-SNAPSHOT/bin/rest_module (No such file or directory)

2016-10-10 20:30:37.297 [Thread-10] ERROR com.bagri.rest.BagriRestServer - buildSchemaConfig; error processing module: rest_module
com.bagri.xdm.api.XDMException: java.io.FileNotFoundException: /home/bagri/apps/bagri-1.1.0-SNAPSHOT/bin/rest_module (No such file or directory)
/home/bagri/apps/bagri-1.1.0-SNAPSHOT/bin/rest_module (No such file or directory)

	at com.bagri.xquery.saxon.XQCompilerImpl.getModuleExpression(XQCompilerImpl.java:301) ~[bagri-xquery-saxon-1.1.0-SNAPSHOT.jar:na]
	at com.bagri.xquery.saxon.XQCompilerImpl.getRestFunctions(XQCompilerImpl.java:337) ~[bagri-xquery-saxon-1.1.0-SNAPSHOT.jar:na]
	at com.bagri.rest.BagriRestServer.buildDynamicResources(BagriRestServer.java:275) [bagri-rest-1.1.0-SNAPSHOT.jar:na]
	at com.bagri.rest.BagriRestServer.buildSchemaConfig(BagriRestServer.java:258) [bagri-rest-1.1.0-SNAPSHOT.jar:na]
	at com.bagri.rest.BagriRestServer.access$100(BagriRestServer.java:47) [bagri-rest-1.1.0-SNAPSHOT.jar:na]
	at com.bagri.rest.BagriRestServer$2.run(BagriRestServer.java:114) [bagri-rest-1.1.0-SNAPSHOT.jar:na]
```
TODO: add rest_module to distributive package, fix path

**Comment by dsukhoroslov** [comment]
fixed
